"""add status  column to project

Revision ID: 863638442516
Revises: 9e7c3de757f9
Create Date: 2026-02-05 19:38:32.893941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863638442516'
down_revision = '9e7c3de757f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=120), server_default='draft', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
